
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TOSHIBA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_label_filePemain = new javax.swing.JLabel();
        home_label_jadwalKandidat = new javax.swing.JLabel();
        home_label_jadwalTempat = new javax.swing.JLabel();
        home_text_filePemain = new javax.swing.JTextField();
        home_text_jadwalKandidat = new javax.swing.JTextField();
        home_text_jadwalTempat = new javax.swing.JTextField();
        home_button_filePemain = new javax.swing.JButton();
        home_button_jadwalKandidat = new javax.swing.JButton();
        home_button_jadwalTempat = new javax.swing.JButton();
        home_button_bikin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nanto-Scheduling");
        setLocationByPlatform(true);
        setName("home_frame"); // NOI18N
        setResizable(false);

        home_label_filePemain.setText("File Pemain");

        home_label_jadwalKandidat.setText("Jadwal Kandidat");

        home_label_jadwalTempat.setText("Jadwal Tempat");

        home_button_filePemain.setText("Buka");
        home_button_filePemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_button_filePemainActionPerformed(evt);
            }
        });

        home_button_jadwalKandidat.setText("Buka");
        home_button_jadwalKandidat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_button_jadwalKandidatActionPerformed(evt);
            }
        });

        home_button_jadwalTempat.setText("Buka");
        home_button_jadwalTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_button_jadwalTempatActionPerformed(evt);
            }
        });

        home_button_bikin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        home_button_bikin.setText("BIKIN");
        home_button_bikin.setActionCommand("");
        home_button_bikin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_button_bikinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(home_button_bikin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home_label_jadwalKandidat)
                            .addComponent(home_label_jadwalTempat)
                            .addComponent(home_label_filePemain))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(home_text_filePemain)
                            .addComponent(home_text_jadwalKandidat)
                            .addComponent(home_text_jadwalTempat, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(home_button_jadwalKandidat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_button_filePemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_button_jadwalTempat, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_label_filePemain)
                    .addComponent(home_text_filePemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_button_filePemain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_label_jadwalKandidat)
                    .addComponent(home_text_jadwalKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_button_jadwalKandidat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_label_jadwalTempat)
                    .addComponent(home_text_jadwalTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_button_jadwalTempat))
                .addGap(43, 43, 43)
                .addComponent(home_button_bikin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_button_filePemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_button_filePemainActionPerformed
        // Inisiasi
        JFileChooser fc = new JFileChooser();
        
        // Membuka dialog open file
        int rVal = fc.showOpenDialog(Home.this);
        
        if (rVal == JFileChooser.APPROVE_OPTION) {
            home_text_filePemain.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_home_button_filePemainActionPerformed

    private void home_button_jadwalKandidatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_button_jadwalKandidatActionPerformed
        // Inisiasi
        JFileChooser fc = new JFileChooser();
        
        // Membuka dialog open file
        int rVal = fc.showOpenDialog(Home.this);
        
        if (rVal == JFileChooser.APPROVE_OPTION) {
            home_text_filePemain.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_home_button_jadwalKandidatActionPerformed

    private void home_button_jadwalTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_button_jadwalTempatActionPerformed
        // Inisiasi
        JFileChooser fc = new JFileChooser();
        
        // Membuka dialog open file
        int rVal = fc.showOpenDialog(Home.this);
        
        if (rVal == JFileChooser.APPROVE_OPTION) {
            home_text_filePemain.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_home_button_jadwalTempatActionPerformed

    private void home_button_bikinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_button_bikinActionPerformed
        new GA().setVisible(true);
    }//GEN-LAST:event_home_button_bikinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_button_bikin;
    private javax.swing.JButton home_button_filePemain;
    private javax.swing.JButton home_button_jadwalKandidat;
    private javax.swing.JButton home_button_jadwalTempat;
    private javax.swing.JLabel home_label_filePemain;
    private javax.swing.JLabel home_label_jadwalKandidat;
    private javax.swing.JLabel home_label_jadwalTempat;
    private javax.swing.JTextField home_text_filePemain;
    private javax.swing.JTextField home_text_jadwalKandidat;
    private javax.swing.JTextField home_text_jadwalTempat;
    // End of variables declaration//GEN-END:variables
}
